spring: 
  profiles: 
    active: 
      -dev

---

spring: 
  profiles: dev  #开发环境
  application: 
    name: xxw-cloud-config-dev

---

spring: 
  profiles: test #测试环境
  application: 
    name: xxw-cloud-config-test

    #UTF-8保存